version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "4000:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
