version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    environment:
      - DEBUG=TRUE

      # Secret environment variables. These values are for development only -- DO NOT copy these values into production.
      - DJANGO_SECRET_KEY=@+g_1+9i%#!6mi05jgui9tb^fenhw^pkdaxd)&3h&0t^se9^py
