# Generated by Django 2.1.4 on 2019-03-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chatserver", "0005_auto_20190228_0926")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password_hash",
            field=models.CharField(max_length=82),
        )
    ]
